/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          username?: parameters["rowFilter.profiles.username"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          website?: parameters["rowFilter.profiles.website"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          username?: parameters["rowFilter.profiles.username"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          website?: parameters["rowFilter.profiles.website"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          username?: parameters["rowFilter.profiles.username"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          website?: parameters["rowFilter.profiles.website"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/projects": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          owner_user_id?: parameters["rowFilter.projects.owner_user_id"];
          name?: parameters["rowFilter.projects.name"];
          created_at?: parameters["rowFilter.projects.created_at"];
          purpose?: parameters["rowFilter.projects.purpose"];
          what_to_do?: parameters["rowFilter.projects.what_to_do"];
          problems?: parameters["rowFilter.projects.problems"];
          targets?: parameters["rowFilter.projects.targets"];
          needed_help?: parameters["rowFilter.projects.needed_help"];
          project_url?: parameters["rowFilter.projects.project_url"];
          how_to_join?: parameters["rowFilter.projects.how_to_join"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["projects"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          owner_user_id?: parameters["rowFilter.projects.owner_user_id"];
          name?: parameters["rowFilter.projects.name"];
          created_at?: parameters["rowFilter.projects.created_at"];
          purpose?: parameters["rowFilter.projects.purpose"];
          what_to_do?: parameters["rowFilter.projects.what_to_do"];
          problems?: parameters["rowFilter.projects.problems"];
          targets?: parameters["rowFilter.projects.targets"];
          needed_help?: parameters["rowFilter.projects.needed_help"];
          project_url?: parameters["rowFilter.projects.project_url"];
          how_to_join?: parameters["rowFilter.projects.how_to_join"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          owner_user_id?: parameters["rowFilter.projects.owner_user_id"];
          name?: parameters["rowFilter.projects.name"];
          created_at?: parameters["rowFilter.projects.created_at"];
          purpose?: parameters["rowFilter.projects.purpose"];
          what_to_do?: parameters["rowFilter.projects.what_to_do"];
          problems?: parameters["rowFilter.projects.problems"];
          targets?: parameters["rowFilter.projects.targets"];
          needed_help?: parameters["rowFilter.projects.needed_help"];
          project_url?: parameters["rowFilter.projects.project_url"];
          how_to_join?: parameters["rowFilter.projects.how_to_join"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
        };
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    username?: string;
    /** Format: text */
    avatar_url?: string;
    /** Format: text */
    website?: string;
  };
  /** @description Project table */
  projects: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    owner_user_id?: string;
    /** Format: character varying */
    name: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    purpose?: string;
    /** Format: text */
    what_to_do?: string;
    /** Format: text */
    problems?: string;
    /** Format: text */
    targets?: string;
    /** Format: text */
    needed_help?: string;
    /** Format: character varying */
    project_url?: string;
    /** Format: text */
    how_to_join?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    updated_at?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.profiles.updated_at": string;
  /** Format: text */
  "rowFilter.profiles.username": string;
  /** Format: text */
  "rowFilter.profiles.avatar_url": string;
  /** Format: text */
  "rowFilter.profiles.website": string;
  /** @description projects */
  "body.projects": definitions["projects"];
  /** Format: bigint */
  "rowFilter.projects.id": string;
  /** Format: uuid */
  "rowFilter.projects.owner_user_id": string;
  /** Format: character varying */
  "rowFilter.projects.name": string;
  /** Format: timestamp with time zone */
  "rowFilter.projects.created_at": string;
  /** Format: text */
  "rowFilter.projects.purpose": string;
  /** Format: text */
  "rowFilter.projects.what_to_do": string;
  /** Format: text */
  "rowFilter.projects.problems": string;
  /** Format: text */
  "rowFilter.projects.targets": string;
  /** Format: text */
  "rowFilter.projects.needed_help": string;
  /** Format: character varying */
  "rowFilter.projects.project_url": string;
  /** Format: text */
  "rowFilter.projects.how_to_join": string;
  /** Format: timestamp without time zone */
  "rowFilter.projects.updated_at": string;
}

export interface operations {}

export interface external {}
