-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.joined_projects
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    profile_id uuid NOT NULL,
    project_id uuid NOT NULL,
    CONSTRAINT joined_projects_pkey PRIMARY KEY (id),
    CONSTRAINT joined_projects_profile_id_fkey FOREIGN KEY (profile_id)
        REFERENCES public.profiles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT joined_projects_project_id_fkey FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.joined_projects
    OWNER to postgres;

GRANT ALL ON TABLE public.joined_projects TO anon;

GRANT ALL ON TABLE public.joined_projects TO authenticated;

GRANT ALL ON TABLE public.joined_projects TO postgres;

GRANT ALL ON TABLE public.joined_projects TO service_role;

COMMENT ON TABLE public.joined_projects
    IS 'profile and project join table';
