-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE EXTENSION IF NOT EXISTS moddatetime
	SCHEMA "extensions";

CREATE TRIGGER handle_updated_at_projects
    BEFORE UPDATE 
    ON public.projects
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');
